# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2416320f36ad6c08c5a3cbf99810e8efa7439a4a027700815f886644f294eea2595bf160713f2b773d9ebc8fe98d51df41b6392950779ee8250683a49caa33d9

test:
  secret_key_base: bb38444da3c74c448a7a7dbc62c8d6f7facac651a4741401246d0ecde3adb1d33d4d764e8048bfeeac5dd4361b8b36bba46ebfba490de910a98cfc04c7b2940d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
